import os
import json
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModel
import torch.nn as nn

# ============================================================
# TEXT EMBEDDING PIPELINE — v3
# Key changes over v2:
#   - au_descriptions.json now has {"healthy": ..., "parkinson": ...}
#     per AU (generated by generate_llm_descriptions.py v3).
#   - Produces TWO separate embedding files:
#       text_embeddings_healthy.npy    shape (18, 512)
#       text_embeddings_parkinson.npy  shape (18, 512)
#     The training model loads both and uses them independently
#     in DDCA/CDCA so each modality gets its own clean alignment
#     signal instead of a blended average.
#   - Everything else unchanged from v2:
#       PubMedBERT, [CLS] pooling, 3-layer Transformer,
#       L2 normalisation per row.
# ============================================================

DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BERT_MODEL = "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
D_IN       = 768   # PubMedBERT hidden size
D_MODEL    = 512   # projection output
NUM_LAYERS = 3
NUM_HEADS  = 8     # 768 / 8 = 96 — valid

# AU order must match FEATURES list in all training scripts
FEATURES = [
    "AU01", "AU02", "AU04", "AU05", "AU06", "AU07", "AU45",
    "AU09", "AU10", "AU12", "AU14", "AU15", "AU20", "AU23",
    "AU24", "AU25", "AU26", "AU17"
]


class AUTransformer(nn.Module):
    """3-layer Transformer: contextualises 18 per-AU BERT embeddings,
    then projects D_IN → D_MODEL."""
    def __init__(self, d_in, d_out, n_layers, n_heads):
        super().__init__()
        enc_layer = nn.TransformerEncoderLayer(
            d_model=d_in, nhead=n_heads,
            dim_feedforward=d_in * 4, dropout=0.1, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=n_layers)
        self.projection  = nn.Linear(d_in, d_out)

    def forward(self, x):
        return self.projection(self.transformer(x))   # (1, 18, D_MODEL)


def encode_sentences(sentences, tokenizer, bert, transformer, label):
    """Encode a list of 18 sentences → L2-normalised (18, 512) array."""
    print(f"\nEncoding {label} descriptions with PubMedBERT...")
    h_list = []
    with torch.no_grad():
        for i, sent in enumerate(sentences):
            inputs = tokenizer(sent, return_tensors="pt", padding=True,
                               truncation=True, max_length=256).to(DEVICE)
            cls_emb = bert(**inputs).last_hidden_state[:, 0, :]   # (1, 768)
            h_list.append(cls_emb)
            print(f"  [{i+1:02d}/18] {FEATURES[i]} — OK")

    H = torch.stack(h_list, dim=1)   # (1, 18, 768)
    print(f"  Stacked shape: {H.shape}")

    print(f"  Contextualising with 3-layer Transformer...")
    with torch.no_grad():
        Z = transformer(H).squeeze(0).cpu().numpy()   # (18, 512)

    # L2 normalise each row
    norms       = np.linalg.norm(Z, axis=-1, keepdims=True)
    Z_norm      = Z / (norms + 1e-8)
    print(f"  Row-norm range: {norms.min():.3f} – {norms.max():.3f}  →  normalised")
    return Z_norm


def main():
    if not os.path.exists("au_descriptions.json"):
        print("❌ au_descriptions.json not found — run generate_llm_descriptions.py first.")
        return

    with open("au_descriptions.json", "r") as f:
        descriptions = json.load(f)

    # Validate v3 format
    sample = next(iter(descriptions.values()))
    if not isinstance(sample, dict) or "healthy" not in sample:
        print("❌ au_descriptions.json appears to be v2 format (single string per AU).")
        print("   Re-run generate_llm_descriptions.py (v3) to regenerate with healthy/parkinson split.")
        return

    # Build ordered sentence lists matching FEATURES order
    healthy_sentences   = [descriptions[au]["healthy"]   for au in FEATURES]
    parkinson_sentences = [descriptions[au]["parkinson"] for au in FEATURES]

    print(f"Model  : {BERT_MODEL}")
    print(f"D_IN   : {D_IN}   D_MODEL : {D_MODEL}")
    print(f"Device : {DEVICE}")

    # Load PubMedBERT (shared for both passes)
    print(f"\nLoading {BERT_MODEL}...")
    tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL)
    bert      = AutoModel.from_pretrained(BERT_MODEL).to(DEVICE)
    bert.eval()

    # Shared Transformer (randomly initialised — acts as a fixed
    # inter-AU contextualiser; same weights for both healthy/PD
    # so AU spatial relationships are modelled consistently)
    transformer = AUTransformer(D_IN, D_MODEL, NUM_LAYERS, NUM_HEADS).to(DEVICE)
    transformer.eval()

    # Encode both modalities
    Z_healthy   = encode_sentences(healthy_sentences,   tokenizer, bert, transformer, "HEALTHY")
    Z_parkinson = encode_sentences(parkinson_sentences, tokenizer, bert, transformer, "PARKINSON")

    # Save
    np.save("text_embeddings_healthy.npy",   Z_healthy)
    np.save("text_embeddings_parkinson.npy", Z_parkinson)

    # Also save a legacy combined file (mean of both) for backward compat
    Z_combined = (Z_healthy + Z_parkinson) / 2.0
    norms = np.linalg.norm(Z_combined, axis=-1, keepdims=True)
    Z_combined = Z_combined / (norms + 1e-8)
    np.save("text_embeddings.npy", Z_combined)

    # AU order reference
    with open("au_order.json", "w") as f:
        json.dump(FEATURES, f)

    # Sanity check
    print("\n" + "="*50)
    print("SAVED FILES:")
    print(f"  text_embeddings_healthy.npy   shape {Z_healthy.shape}")
    print(f"  text_embeddings_parkinson.npy shape {Z_parkinson.shape}")
    print(f"  text_embeddings.npy           shape {Z_combined.shape}  (mean, legacy)")
    print(f"  au_order.json")
    for name, Z in [("healthy", Z_healthy), ("parkinson", Z_parkinson)]:
        norms = np.linalg.norm(Z, axis=-1)
        print(f"  {name} row norms — min {norms.min():.4f}  max {norms.max():.4f}  (should be ~1.0)")
    print("\n✅ All done. Ready for Fusion_NoAugmentation.py training.")


if __name__ == "__main__":
    main()
